# Server API: http://localhost:5678/api

###
# User login
POST http://localhost:5678/api/users/login
Content-Type: application/json

{
  "email": "sophie.bluel@test.tld",
  "password": "S0phie"
}

###
# User works
GET http://localhost:5678/api/works
Authorization: Bearer {{TOKEN}}


###
# User categories
GET http://localhost:5678/api/categories
