# Sophie Bluel Portfolio API Documentation
@baseUrl = http://localhost:5678/api

### Authentication
# @name login
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "sophie.bluel@test.tld",
    "password": "S0phie"
}

### Works
# Get all works
GET {{baseUrl}}/works
Authorization: Bearer {{login.response.body.token}}

### Categories 
# Get all categories
GET {{baseUrl}}/categories

### Works Management
# Add new work
POST {{baseUrl}}/works
Authorization: Bearer {{login.response.body.token}}
Content-Type: multipart/form-data

# Delete work
DELETE {{baseUrl}}/works/:id
Authorization: Bearer {{login.response.body.token}}
